title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: Octo
  repo: boilerplate
# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:

- type: respond
  with: 01_first-response.md


# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title:  the title of the step, shown to the learner in the course progress page
  description:   description of the step, shown to the learner in the course progress page
  event:  	issue_commented.created
  actions: # a list of the actions that will occur when the step is triggered by an event
  
  type: gate                            # using the gate action
  left: '%payload.pull_request.title%'  # get the title from the pull request object inside of the payload
  operator: ===                         # check for strict equality, see more at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Identity
  right: "Add name to README"             # this is the expected value

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
 - title:  the title of the step, shown to the learner in the course progress page
  description:  a description of the step, shown to the learner in the course progress page
  event: push
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
 - title:  the title of the step, shown to the learner in the course progress page
  description:  a description of the step, shown to the learner in the course progress page
  event: pull_request
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
 - title:  the title of the step, shown to the learner in the course progress page
   description:  a description of the step, shown to the learner in the course progress page
  event: pull_request.synchronize
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
 - title:  the title of the step, shown to the learner in the course progress page
  description:  a description of the step, shown to the learner in the course progress page
  event: status
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

